import { 
    autoGeneratedHashKey,
    attribute,
    rangeKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';
import { IIdea } from '../iidea.entity';

@table('ideas')
export class Idea implements IIdea {
    
    @autoGeneratedHashKey()
    id: string;

    @rangeKey()
    createdAt: Date;

    @attribute()
    name: string;

    @attribute()
    description: string;
}