import { 
    autoGeneratedHashKey,
    attribute,
    rangeKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';
import { IStepProject } from '../istep-project.entity';

@table('step_projects')
export class StepProject implements IStepProject {
    
    @autoGeneratedHashKey()
    id: string;
    
    @rangeKey()
    createdAt: Date;

    @attribute()
    name: string;

    @attribute()
    description: string;
}